version: '2'

services:
  rocketchat:
    image: rocket.chat
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  bot:
    image: python:3.6
    command: bash -c "pip install -e /app && python3 /app/examples/bot.py"
    tty: true
    environment:
      - ROCKET_URL=rocketchat:3000
      - BOT_USERNAME=bot
      - BOT_PASSWORD=bot
    volumes:
      - ./:/app

